services:
  flux-eco-sftp-sidecar:
    image: fluxms/flux-eco-sftp-sidecar:latest
    environment:
      - SFTP_SHARE_LOGIN_FILE=/run/secrets/sftp_share_login_1
      - SFTP_SHARE_PASSWORD_FILE=/run/secrets/sftp_share_password_1
    secrets:
      - sftp_share_login_1
      - sftp_share_password_1
    ports:
      - 127.1.2.3:2222:22
    volumes:
      - ./share/example:/home/share
      - ./keys:/etc/ssh/keys
secrets:
  sftp_share_login_1:
    file: "sftp_share_login_1"
  sftp_share_password_1:
    file: "sftp_share_password_1"
